//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bu.Web.Admin.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bu.Web.Admin.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Vice Admiral (R) Asif Khaliq HI(M)
        ///
        ///{ class=&quot;text-justify&quot; }
        ///Bahria University is one of the leading public sector universities of Pakistan, which is dedicated to meet many complex challenges facing us today. The university has campuses, research institutes and colleges all over Pakistan which work towards grooming today’s youth into becoming tomorrow’s leaders. We provide a platform for promising minds to come together, pioneer new thought and serve the world around them. And for this we provide the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buho_About_RectorMessage {
            get {
                return ResourceManager.GetString("Buho_About_RectorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Vision &amp; Mission
        ///
        ///### Vision
        ///
        ///{ class=&quot;text-justify&quot; }
        ///To become a knowledge and creativity driven international university that contributes towards development of society.
        ///
        ///### Mission
        ///
        ///{ class=&quot;text-justify&quot; }
        ///To ensure academic excellence through deliverance of quality education and applied research in a collegiate environment having strong linkages with industry and international community to meet the societal challenges.
        ///
        ///### Core Values
        ///
        ///1. Integrity
        ///1. Creativity
        ///1. Excellence
        ///1.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buho_About_VisionAndMission {
            get {
                return ResourceManager.GetString("Buho_About_VisionAndMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## ATTRIBUTES
        ///
        ///- Federally Chartered
        ///- HEC recognized
        ///- Engineering Programs are accredited by PEC
        ///- Medical Programs are recognized by PMDC
        ///- LLB Program recognized by PBC
        ///- Multi – Disciplinary University
        ///- Highly qualified Faculty
        ///- Custom-built Campuses
        ///- State of the art laboratories
        ///- Well-stocked Libraries
        ///- Classroom and research based teachings
        ///- Career Office
        ///- Internship Opportunities
        ///- Good Student to Faculty ratio
        ///- Medical cover for students/staff/faculty
        ///- Student Resource Ce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buho_About_WhyBahria {
            get {
                return ResourceManager.GetString("Buho_About_WhyBahria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carousel_1920x600px {
            get {
                object obj = ResourceManager.GetObject("Carousel_1920x600px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
